### PR TITLE
Update makefile android

### PR DESCRIPTION
**Pull request by planetis-m**
Warning not tested.

### CODE REVIEW

**Comment by raysan5** [comment]
@planetis-m Thanks for the review! I will wait for test results before merging...

**Comment by planetis-m** [comment]
Then someone can volunteer? I don't have a Windows machine.

**Comment by raysan5** [comment]
@planetis-m I'm asking in raylib Discord

**Comment by raysan5** [comment]
I'm not merging due to not being tested.

**Pull request closed without merging**
